#!/bin/bash

#dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

swww init
swww img ~/.config/hypr/wallpapers/1.jpg

eww daemon --config "$HOME/.config/eww/menu" 

nm-applet &
blueman-applet
